### ISSUE TITLE
Redundant code?

### ISSUE THREAD

**Issue by perlindgren** [cvhariharan/smoke-rs#1]
Hi

I looked at your code example and got some (maybe stupid) questions. 

1. the `.insert_resource(Msaa { samples: 8 })`, seems unnecessary. (Not sure I could see any difference, to what is `Msaa` applied here?)

2. the `.add_plugin(ShapePlugin)` and 
```rust
let shape = shapes::Circle {
         radius: 15.0,
         center: Default::default(),
};
``` 

Looks like the code is unused. Maybe some leftover from experimentation? (The example works without the code.)

3. The `Alive` struct, and corresponding code. Is that really put to use, as you despawn the entitiy on expired lifetime. (I tried removing `Alive` and related code, and it still works.

Besides that, the example was easy to follow and makes full sense. Perhaps removing redundant code could make it even clearer and more to the point.

Thanks for your efforts.
/Per

**Comment by cvhariharan** [comment]
Hello @perlindgren, thanks for pointing this out. Yes, there is a lot of redundant code which I didn't clean up. Will do the clean up soon and close this issue once its complete.
